import type { Metadata } from "next";
import { JetBrains_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({ //font-jetbrains-mono", ponemos aqui las fuentes que queremos usar en nuestra app, en este caso la fuente JetBrains Mono y Noto Sans JP
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSansJP.variable} ${jetbrainsMono.variable} h-full antialiased`} // Aplicamos las clases de las fuentes tambien aqui en el html para que se apliquen a toda la app
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
